In [1]:
import pandas as pd
import gzip

In [2]:
with gzip.open(
    "../data/raw/ensembl/Homo_sapiens.GRCh38.116.gtf.gz",
    "rt"
) as f:

    for i in range(20):
        print(f.readline())

#!genome-build GRCh38.p14

#!genome-version GRCh38

#!genome-date 2013-12

#!genome-build-accession GCA_000001405.29

#!genebuild-last-updated 2025-11

1	havana	gene	5301928	5307394	.	-	.	gene_id "ENSG00000284616"; gene_version "1"; gene_source "havana"; gene_biotype "lncRNA";

1	havana	transcript	5301928	5307394	.	-	.	gene_id "ENSG00000284616"; gene_version "1"; transcript_id "ENST00000641871"; transcript_version "1"; gene_source "havana"; gene_biotype "lncRNA"; transcript_source "havana"; transcript_biotype "lncRNA"; tag "gencode_basic"; tag "gencode_primary"; tag "Ensembl_canonical";

1	havana	exon	5306942	5307394	.	-	.	gene_id "ENSG00000284616"; gene_version "1"; transcript_id "ENST00000641871"; transcript_version "1"; exon_number "1"; gene_source "havana"; gene_biotype "lncRNA"; transcript_source "havana"; transcript_biotype "lncRNA"; exon_id "ENSE00003812690"; exon_version "1"; tag "gencode_basic"; tag "gencode_primary"; tag "Ensembl_canonical";

1	havana	exon	5304401	5305029	.	-	.	gene_id "ENSG00000284616"; gene_version "1"; transcript_id "ENST00000641871"; transcript_version "1"; exon_number "2"; gene_source "havana"; gene_biotype "lncRNA"; transcript_source "havana"; transcript_biotype "lncRNA"; exon_id "ENSE00003812264"; exon_version "1"; tag "gencode_basic"; tag "gencode_primary"; tag "Ensembl_canonical";

1	havana	exon	5303328	5303393	.	-	.	gene_id "ENSG00000284616"; gene_version "1"; transcript_id "ENST00000641871"; transcript_version "1"; exon_number "3"; gene_source "havana"; gene_biotype "lncRNA"; transcript_source "havana"; transcript_biotype "lncRNA"; exon_id "ENSE00003813945"; exon_version "1"; tag "gencode_basic"; tag "gencode_primary"; tag "Ensembl_canonical";

1	havana	exon	5301928	5302004	.	-	.	gene_id "ENSG00000284616"; gene_version "1"; transcript_id "ENST00000641871"; transcript_version "1"; exon_number "4"; gene_source "havana"; gene_biotype "lncRNA"; transcript_source "havana"; transcript_biotype "lncRNA"; exon_id "ENSE00003812912"; exon_version "1"; tag "gencode_basic"; tag "gencode_primary"; tag "Ensembl_canonical";

1	havana	gene	5492978	5494674	.	+	.	gene_id "ENSG00000260972"; gene_version "1"; gene_source "havana"; gene_biotype "lncRNA";

1	havana	transcript	5492978	5494674	.	+	.	gene_id "ENSG00000260972"; gene_version "1"; transcript_id "ENST00000564261"; transcript_version "1"; gene_source "havana"; gene_biotype "lncRNA"; transcript_source "havana"; transcript_biotype "lncRNA"; tag "gencode_basic"; tag "gencode_primary"; tag "Ensembl_canonical"; transcript_support_level "NA";

1	havana	exon	5492978	5494674	.	+	.	gene_id "ENSG00000260972"; gene_version "1"; transcript_id "ENST00000564261"; transcript_version "1"; exon_number "1"; gene_source "havana"; gene_biotype "lncRNA"; transcript_source "havana"; transcript_biotype "lncRNA"; exon_id "ENSE00002600197"; exon_version "1"; tag "gencode_basic"; tag "gencode_primary"; tag "Ensembl_canonical"; transcript_support_level "NA";

1	havana	gene	4175528	4175899	.	-	.	gene_id "ENSG00000229280"; gene_version "1"; gene_name "EEF1DP6"; gene_source "havana"; gene_biotype "processed_pseudogene";

1	havana	transcript	4175528	4175899	.	-	.	gene_id "ENSG00000229280"; gene_version "1"; transcript_id "ENST00000449232"; transcript_version "1"; gene_name "EEF1DP6"; gene_source "havana"; gene_biotype "processed_pseudogene"; transcript_name "EEF1DP6-201"; transcript_source "havana"; transcript_biotype "processed_pseudogene"; tag "gencode_basic"; tag "gencode_primary"; tag "Ensembl_canonical"; transcript_support_level "NA";

1	havana	exon	4175528	4175899	.	-	.	gene_id "ENSG00000229280"; gene_version "1"; transcript_id "ENST00000449232"; transcript_version "1"; exon_number "1"; gene_name "EEF1DP6"; gene_source "havana"; gene_biotype "processed_pseudogene"; transcript_name "EEF1DP6-201"; transcript_source "havana"; transcript_biotype "processed_pseudogene"; exon_id "ENSE00001708896"; exon_version "1"; tag "gencode_basic"; tag "gencode_primary"; tag "Ensembl_canonical"; transcript_support_level "NA";

1	havana	gene	4571481	4594016	.	+	.	gene_id "ENSG00000232596"; gene_version "3"; gene_name "LINC01646"; gene_source "havana"; gene_biotype "lncRNA";

1	havana	transcript	4571481	4594009	.	+	.	gene_id "ENSG00000232596"; gene_version "3"; transcript_id "ENST00000634256"; transcript_version "1"; gene_name "LINC01646"; gene_source "havana"; gene_biotype "lncRNA"; transcript_name "LINC01646-202"; transcript_source "havana"; transcript_biotype "lncRNA"; tag "gencode_primary"; tag "Ensembl_canonical"; transcript_support_level "5";

1	havana	exon	4571481	4571629	.	+	.	gene_id "ENSG00000232596"; gene_version "3"; transcript_id "ENST00000634256"; transcript_version "1"; exon_number "1"; gene_name "LINC01646"; gene_source "havana"; gene_biotype "lncRNA"; transcript_name "LINC01646-202"; transcript_source "havana"; transcript_biotype "lncRNA"; exon_id "ENSE00003786837"; exon_version "1"; tag "gencode_primary"; tag "Ensembl_canonical"; transcript_support_level "5";

In [3]:
import gzip

with gzip.open(
    "../data/raw/ensembl/Homo_sapiens.GRCh38.116.gtf.gz",
    "rt"
) as f:

    for line in f:
        if line.startswith("#"):
            continue

        fields = line.strip().split("\t")

        feature_type = fields[2]

        if feature_type == "gene":
            print(line)
            break

1	havana	gene	5301928	5307394	.	-	.	gene_id "ENSG00000284616"; gene_version "1"; gene_source "havana"; gene_biotype "lncRNA";

In [4]:
rows = []

with gzip.open(
    "../data/raw/ensembl/Homo_sapiens.GRCh38.116.gtf.gz",
    "rt"
) as f:

    for line in f:

        if line.startswith("#"):
            continue

        fields = line.strip().split("\t")

        if fields[2] != "gene":
            continue

        chromosome = fields[0]
        start_position = int(fields[3])
        end_position = int(fields[4])

        attributes = fields[8]

In [6]:
rows = []

with gzip.open(
    "../data/raw/ensembl/Homo_sapiens.GRCh38.116.gtf.gz",
    "rt"
) as f:

    for line in f:

        if line.startswith("#"):
            continue

        fields = line.strip().split("\t")

        if fields[2] != "gene":
            continue

        chromosome = fields[0]
        start_position = int(fields[3])
        end_position = int(fields[4])

        attributes = fields[8]

        gene_name = None

        for item in attributes.split(";"):

            item = item.strip()

            if item.startswith("gene_name"):
                gene_name = item.split('"')[1]

        rows.append({
            "gene_symbol": gene_name,
            "chromosome": chromosome,
            "start_position": start_position,
            "end_position": end_position
        })

In [7]:
import pandas as pd

ensembl_df = pd.DataFrame(rows)

ensembl_df.head()

  gene_symbol chromosome  start_position  end_position
0         NaN          1         5301928       5307394
1         NaN          1         5492978       5494674
2     EEF1DP6          1         4175528       4175899
3   LINC01646          1         4571481       4594016
4   LINC02782          1         5086459       5090899

In [8]:
rows[0]

{'gene_symbol': None,
 'chromosome': '1',
 'start_position': 5301928,
 'end_position': 5307394}

In [9]:
rows[1]

{'gene_symbol': None,
 'chromosome': '1',
 'start_position': 5492978,
 'end_position': 5494674}

In [10]:
ensembl_df.isnull().sum()

gene_symbol       35483
chromosome            0
start_position        0
end_position          0
dtype: int64

In [11]:
ensembl_df = ensembl_df.dropna(subset=["gene_symbol"])

In [12]:
ensembl_df = ensembl_df.reset_index(drop=True)

In [13]:
ensembl_df.head()

  gene_symbol chromosome  start_position  end_position
0     EEF1DP6          1         4175528       4175899
1   LINC01646          1         4571481       4594016
2   LINC02782          1         5086459       5090899
3   LINC02781          1         4973381       4981568
4    MTCYBP45          1        11425257      11425821

In [14]:
ensembl_df.isnull().sum()

gene_symbol       0
chromosome        0
start_position    0
end_position      0
dtype: int64

In [15]:
ensembl_df.shape

(43458, 4)

In [ ]:
ensembl_df.to_csv(
    "../data/interim/ensembl_tables/gene_coordinates_table.csv",
    index=False
)

: